// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: start/phone.proto
// Protobuf Java Version: 4.29.3

package com.example.start;

public interface PhoneOrBuilder extends
    // @@protoc_insertion_point(interface_extends:start.Phone)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string number = 1;</code>
   * @return The number.
   */
  java.lang.String getNumber();
  /**
   * <code>string number = 1;</code>
   * @return The bytes for number.
   */
  com.google.protobuf.ByteString
      getNumberBytes();
}
