// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: newProto/contactsNew.proto
// Protobuf Java Version: 4.29.3

package com.example.newProto;

public final class ContactProtos {
  private ContactProtos() {}
  static {
    com.google.protobuf.RuntimeVersion.validateProtobufGencodeVersion(
      com.google.protobuf.RuntimeVersion.RuntimeDomain.PUBLIC,
      /* major= */ 4,
      /* minor= */ 29,
      /* patch= */ 3,
      /* suffix= */ "",
      ContactProtos.class.getName());
  }
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_newProto_PeopleInfo_descriptor;
  static final 
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_newProto_PeopleInfo_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_newProto_Contacts_descriptor;
  static final 
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_newProto_Contacts_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\032newProto/contactsNew.proto\022\010newProto\032\021" +
      "start/phone.proto\"D\n\nPeopleInfo\022\014\n\004name\030" +
      "\001 \001(\t\022\013\n\003age\030\002 \001(\005\022\033\n\005phone\030\003 \003(\0132\014.star" +
      "t.Phone\"2\n\010Contacts\022&\n\010contacts\030\001 \003(\0132\024." +
      "newProto.PeopleInfoB\'\n\024com.example.newPr" +
      "otoB\rContactProtosP\001b\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
          com.example.start.PhoneProtos.getDescriptor(),
        });
    internal_static_newProto_PeopleInfo_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_newProto_PeopleInfo_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_newProto_PeopleInfo_descriptor,
        new java.lang.String[] { "Name", "Age", "Phone", });
    internal_static_newProto_Contacts_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_newProto_Contacts_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_newProto_Contacts_descriptor,
        new java.lang.String[] { "Contacts", });
    descriptor.resolveAllFeaturesImmutable();
    com.example.start.PhoneProtos.getDescriptor();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
